# Generated by Django 3.1.7 on 2021-03-13 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digipackDB', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='credentials',
        ),
    ]
