# Generated by Django 3.1.7 on 2021-04-28 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentId', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('credentials', models.JSONField(default='')),
            ],
        ),
    ]
