# Generated by Django 3.1.7 on 2021-05-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20210513_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacherId', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('credentials', models.JSONField(default=str)),
            ],
        ),
    ]
